<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Volunteer;
use Illuminate\Support\Facades\Hash;

class VolunteerSeeder extends Seeder
{
    public function run()
    {
        $volunteers = [
            [
                'name' => 'أحمد العلي',
                'email' => 'ahmad1@example.com',
                'password' => Hash::make('password123'),
                'phone' => '+963944111111',
                'gender' => 'male',
                'age' => 25,
                'nationality' => 'سوري',
                'address' => 'دمشق - المزة',
                'skills' => 'تنظيم فعاليات',
                'experience' => 'سنة واحدة',
                'education_level' => 'جامعي',
                'availability' => 'مسائي',
                'preferred_roles' => 'تنظيم',
                'languages' => 'العربية,الإنجليزية',
                'emergency_contact' => '+963944222222',
                'status' => 'pending',
            ],
            [
                'name' => 'محمد الخطيب',
                'email' => 'moh1@example.com',
                'password' => Hash::make('password123'),
                'phone' => '+963944111112',
                'gender' => 'male',
                'age' => 28,
                'nationality' => 'سوري',
                'address' => 'حلب - الجميلية',
                'skills' => 'إدارة فرق',
                'experience' => '3 سنوات',
                'education_level' => 'جامعي',
                'availability' => 'صباحي',
                'preferred_roles' => 'إشراف',
                'languages' => 'العربية,الإنجليزية',
                'emergency_contact' => '+963944222223',
                'status' => 'pending',
            ],
            [
                'name' => 'سارة يوسف',
                'email' => 'sara1@example.com',
                'password' => Hash::make('password123'),
                'phone' => '+963944111113',
                'gender' => 'female',
                'age' => 22,
                'nationality' => 'سورية',
                'address' => 'اللاذقية - المشروع',
                'skills' => 'تصميم',
                'experience' => 'سنتان',
                'education_level' => 'جامعي',
                'availability' => 'مرن',
                'preferred_roles' => 'تصميم',
                'languages' => 'العربية,الفرنسية',
                'emergency_contact' => '+963944222224',
                'status' => 'pending',
            ],
            [
                'name' => 'ليان الأحمد',
                'email' => 'lian1@example.com',
                'password' => Hash::make('password123'),
                'phone' => '+963944111114',
                'gender' => 'female',
                'age' => 20,
                'nationality' => 'سورية',
                'address' => 'حمص - الوعر',
                'skills' => 'كتابة محتوى',
                'experience' => 'سنة',
                'education_level' => 'جامعي',
                'availability' => 'مسائي',
                'preferred_roles' => 'إعلام',
                'languages' => 'العربية,الإنجليزية',
                'emergency_contact' => '+963944222225',
                'status' => 'pending',
            ],
            [
                'name' => 'رامي درويش',
                'email' => 'rami1@example.com',
                'password' => Hash::make('password123'),
                'phone' => '+963944111115',
                'gender' => 'male',
                'age' => 30,
                'nationality' => 'سوري',
                'address' => 'طرطوس - الكورنيش',
                'skills' => 'محاسبة',
                'experience' => '5 سنوات',
                'education_level' => 'جامعي',
                'availability' => 'صباحي',
                'preferred_roles' => 'مالية',
                'languages' => 'العربية',
                'emergency_contact' => '+963944222226',
                'status' => 'pending',
            ],
            [
                'name' => 'نور الحسين',
                'email' => 'noor1@example.com',
                'password' => Hash::make('password123'),
                'phone' => '+963944111116',
                'gender' => 'female',
                'age' => 24,
                'nationality' => 'سورية',
                'address' => 'دمشق - برزة',
                'skills' => 'خدمة مجتمعية',
                'experience' => 'سنتان',
                'education_level' => 'جامعي',
                'availability' => 'مرن',
                'preferred_roles' => 'ميداني',
                'languages' => 'العربية,الإنجليزية',
                'emergency_contact' => '+963944222227',
                'status' => 'pending',
            ],
            [
                'name' => 'خالد العيسى',
                'email' => 'khaled1@example.com',
                'password' => Hash::make('password123'),
                'phone' => '+963944111117',
                'gender' => 'male',
                'age' => 27,
                'nationality' => 'سوري',
                'address' => 'حماة - مركز المدينة',
                'skills' => 'قيادة',
                'experience' => '4 سنوات',
                'education_level' => 'جامعي',
                'availability' => 'مسائي',
                'preferred_roles' => 'تنظيم',
                'languages' => 'العربية',
                'emergency_contact' => '+963944222228',
                'status' => 'pending',
            ],
            [
                'name' => 'ميساء ناصر',
                'email' => 'maysa1@example.com',
                'password' => Hash::make('password123'),
                'phone' => '+963944111118',
                'gender' => 'female',
                'age' => 23,
                'nationality' => 'سورية',
                'address' => 'درعا - البلد',
                'skills' => 'تدريس',
                'experience' => 'سنة',
                'education_level' => 'جامعي',
                'availability' => 'صباحي',
                'preferred_roles' => 'تعليم',
                'languages' => 'العربية',
                'emergency_contact' => '+963944222229',
                'status' => 'pending',
            ],
            [
                'name' => 'ياسر محمود',
                'email' => 'yaser1@example.com',
                'password' => Hash::make('password123'),
                'phone' => '+963944111119',
                'gender' => 'male',
                'age' => 29,
                'nationality' => 'سوري',
                'address' => 'الرقة - الصناعة',
                'skills' => 'إسعافات أولية',
                'experience' => '3 سنوات',
                'education_level' => 'جامعي',
                'availability' => 'مرن',
                'preferred_roles' => 'طوارئ',
                'languages' => 'العربية,الإنجليزية',
                'emergency_contact' => '+963944222230',
                'status' => 'pending',
            ],
            [
                'name' => 'هبة سليمان',
                'email' => 'hiba1@example.com',
                'password' => Hash::make('password123'),
                'phone' => '+963944111120',
                'gender' => 'female',
                'age' => 26,
                'nationality' => 'سورية',
                'address' => 'إدلب - المدينة',
                'skills' => 'تنسيق',
                'experience' => 'سنتان',
                'education_level' => 'جامعي',
                'availability' => 'مسائي',
                'preferred_roles' => 'تنظيم',
                'languages' => 'العربية',
                'emergency_contact' => '+963944222231',
                'status' => 'pending',
            ],
        ];

        foreach ($volunteers as $volunteer) {
            Volunteer::create($volunteer);
        }
    }
}
